version: '3'
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    container_name: frontend-container
    restart: on-failure
    networks:
      - my-network
  
  user_service:
    build: ./fast-api/user
    container_name: user_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast-api/user/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgresql://user_db_admin:user_db_admin@user_db/user_db
    depends_on:
      - user_db
   
  user_db:
    image: postgres:16.0-alpine3.17
    container_name: user_db 
    ports:
      -  "5432:5432"
    environment:
      POSTGRES_USER: user_db_admin
      POSTGRES_PASSWORD: user_db_admin
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: on-failure

  animal_service:
    build: ./fast-api/animal
    container_name: animal_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast-api/animal/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgresql://animal_db_admin:animal_db_admin@animal_db/animal_db
    depends_on:
      - animal_db

  animal_db:
    image: postgres:16.0-alpine3.17
    container_name: animal_db 
    ports:
      -  "5432:5432"
    environment:
      POSTGRES_USER: animal_db_admin
      POSTGRES_PASSWORD: animal_db_admin
      POSTGRES_DB: animal_db
    volumes:
      - animal_db_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  user_db_data:
  animal_db_data:

networks:
  my-network:
    driver: bridge
      
