version: '3'
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    container_name: frontend-container
    restart: on-failure
    networks:
      - my-network
  
  user_service:
    build: ./fast-api/user
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast-api/user/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgresql://user_db_admin:user_db_admin@user_db/user_db
    depends_on:
      - user_db
   
  user_db:
    image: postgres:16.0-alpine3.17
    container_name: postgres-db 
    #host: host.docker.internal
    ports:
      -  "5432:5432"
    environment:
      POSTGRES_USER: user_db_admin
      POSTGRES_PASSWORD: user_db_admin
      POSTGRES_DB: user_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
      
