version: '3'
services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    container_name: frontend-container
    restart: on-failure
    networks:
      - my-network
    # volumes:
    #   - ./front-end/:/app/
  
  user_service:
    build: ./fast-api/user
    container_name: user_service
    command: uvicorn main:app --reload 
    volumes:
      - ./fast-api/user/:/app/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://user_db_admin:user_db_password@user_db_container/user_db_dev
    depends_on:
      - user_db
    # networks:
    #   - my-network
   
  user_db:
    image: postgres:16.0-alpine3.17
    container_name: user_db_container 
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: on-failure
    # networks:
    #   - my-network

volumes:
  user_db_data:

networks:
  my-network:
    driver: bridge
      
