version: '3'
services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    container_name: frontend-container
    command: npm start
    restart: on-failure
    networks:
      - my-network
    # volumes:
    #   - ./front-end/:/app/
  
  user_service:
    build: ./fast-api/user
    container_name: user_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --log-config=logger_conf.yaml
    volumes:
      - ./fast-api/user/:/app/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://user_db_user:user_db_password@user_db/user_db_dev
      - JWT_SECRET_KEY=61f16943d3be6938417e2143bd8c2b9516eadf678d82ea399384085084fd4309
      - AES_SECRET_KEY=a1fd6e8ee6e95b25d8d3bd0f8df50076150cea8eaa808455e24c8e7a44f32609
    depends_on:
      - user_db
    networks:
      - my-network

  user_db:
    image: postgres:16.0-alpine3.17
    container_name: user_db_container
    environment:
      POSTGRES_DB: user_db_dev
      POSTGRES_USER: user_db_user
      POSTGRES_PASSWORD: user_db_password
    ports: 
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - my-network

  animal_service:
    build: ./fast-api/animal
    container_name: animal_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --log-config=logger_conf.yaml
    volumes:
      - ./fast-api/animal/:/app/
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URI=postgresql://animal_db_admin:animal_db_password@animal_db/animal_db_dev
      # TODO: change user_service URL for shelter_service!!!!!
      - SHELTER_SERVICE_HOST_URL=http://user_service:8000/api/v1/users/
    depends_on:
      - animal_db
    networks:
      - my-network

  animal_db:
    image: postgres:16.0-alpine3.17
    container_name: animal_db_container 
    environment:
      POSTGRES_USER: animal_db_admin
      POSTGRES_PASSWORD: animal_db_password
      POSTGRES_DB: animal_db_dev
    ports: 
      - "5433:5432"
    volumes:
      - animal_db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - animal_service
      - user_service
    networks:
      - my-network

  shelter_db:
    image: postgres:16.0-alpine3.17
    container_name: shelter_db_container
    environment:
      POSTGRES_DB: shelter_db_dev
      POSTGRES_USER: shelter_db_user
      POSTGRES_PASSWORD: shelter_db_password
    ports: 
      - "5434:5432"
    volumes:
      - shelter_db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - my-network
  
  shelter_service:
    build: ./fast-api/shelter
    container_name: shelter_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --log-config=logger_conf.yaml
    volumes:
      - ./fast-api/shelter/:/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URI=postgresql://shelter_db_user:shelter_db_password@shelter_db/shelter_db_dev
      - JWT_SECRET_KEY=61f16943d3be6938417e2143bd8c2b9516eadf678d82ea399384085084fd4309
      - AES_SECRET_KEY=a1fd6e8ee6e95b25d8d3bd0f8df50076150cea8eaa808455e24c8e7a44f32609
    depends_on:
      - shelter_db
    networks:
      - my-network

volumes:
  user_db_data:
  animal_db_data:
  shelter_db_data:

networks:
  my-network:
    driver: bridge
      
