name: Docker Image CI

on: push
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start Docker Compose services
      run: |
        docker-compose up -d --build
        docker-compose ps
  user__servcie_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests for user_service (replace with your testing commands)
      run: |
        docker exec user_service pytest

    - name: Stop Docker Compose services
      run: docker-compose down
