name: Docker Image CI

on: 
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Compose Services
        run: docker-compose build

  user_service_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose Services
        run: docker-compose up -d

      - name: Run tests for user_service (replace with your testing commands)
        run: |
          docker exec user_service pytest -sv test_user_unit.py

      - name: Stop Docker Compose Services
        run: docker-compose down

  # animal_shelter_service_test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Start Docker Compose Services
  #       run: docker-compose up -d

  #     - name: Run Python script 
  #       run: |
  #         cd backend/; pip install -r requirements.txt; pytest -s test.py

  #     - name: Stop Docker Compose Services
  #       run: docker-compose down

  animal_service_unit_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose Services
        run: docker-compose up -d

      - name: Run tests for animal_service (replace with your testing commands)
        run: |
          docker exec animal_service pytest -sv 

      - name: Stop Docker Compose Services
        run: docker-compose down

  application_unit_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose Services
        run: docker-compose up -d

      - name: Unit tests for application_service
        run: |
          docker  exec application  pytest -sv

      - name: Stop Docker Compose Services
        run: docker-compose down

  shelter_service_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose Services
        run: docker-compose up -d

      - name: Run Python script 
        run: |
          docker exec shelter_service pytest -sv

      - name: Stop Docker Compose Services
        run: docker-compose down